spring.application.name=comentarios
spring.mongodb.uri=mongodb://localhost:27017/comentariosProyecto
server.port=8503

spring.graphql.graphiql.enabled=true
spring.graphql.http.path= /graphql
spring.graphql.graphiql.path=/comentarios

eureka.client.service-url.defaultZone=http://localhost:8500/eureka/